name: user_auth_app
description: 用户认证系统Flutter前端

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.1.1
  
  # 网络请求
  dio: ^5.3.2
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 路由管理
  go_router: ^12.1.3
  
  # UI组件
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  
  # 图片处理
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # 生物识别
  local_auth: ^2.1.6
  
  # 微信登录
  fluwx: ^5.6.0
  
  # 表单验证
  form_validator: ^2.1.1
  
  # 工具类
  intl: ^0.18.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700 